(() => {
'use strict';
const config=window.GROHE_SUPABASE_CONFIG||{};let client=null,currentUser=null,currentProfile=null,initialized=false;const $=id=>document.getElementById(id),configured=()=>/^https:\/\/.+\.supabase\.co\/?$/i.test(String(config.url||'').trim())&&String(config.anonKey||'').trim().length>20,nowIso=()=>new Date().toISOString();
function msg(text,type='info'){const e=$('authMessage');if(!e)return;e.textContent=text||'';e.dataset.type=type;e.hidden=!text}function profileMsg(text,type='info'){const e=$('profileMessage');if(!e)return;e.textContent=text||'';e.dataset.type=type;e.hidden=!text}
function setView(view){['authSignInView','authSignUpView','authForgotView'].forEach(id=>{const e=$(id);if(e)e.hidden=id!==view});msg('')}
function closeAccount(){const d=$('accountDialog');if(d?.open)d.close()}function openAccount(view='authSignInView'){if(currentUser){openProfile();return}setView(view);const d=$('accountDialog');if(d&&!d.open)d.showModal()}
function updateUi(){const email=currentUser?.email||'';const b=$('btnProfileHeader');if(b){b.textContent=currentUser?(currentProfile?.display_name||email||'Account'):'Sign in';b.classList.toggle('signed-in',!!currentUser)}if($('settingsUserEmail'))$('settingsUserEmail').textContent=email||'Guest · saved on this browser';if($('profileCurrentEmail'))$('profileCurrentEmail').textContent=email||'—';if($('profileEmail'))$('profileEmail').value=email;if($('profileDisplayName'))$('profileDisplayName').value=currentProfile?.display_name||currentUser?.user_metadata?.display_name||'';const initials=(currentProfile?.display_name||email||'U').trim().split(/\s+/).map(x=>x[0]||'').join('').slice(0,2).toUpperCase();if($('profileAvatar'))$('profileAvatar').textContent=initials||'U'}
async function loadProfile(){currentProfile=null;if(!client||!currentUser){updateUi();return}const {data,error}=await client.from('profiles').select('id,display_name,created_at,updated_at').eq('id',currentUser.id).maybeSingle();if(error)console.warn(error.message);if(data)currentProfile=data;else{const r=await client.from('profiles').insert({id:currentUser.id,display_name:currentUser.user_metadata?.display_name||''}).select('id,display_name,created_at,updated_at').single();if(!r.error)currentProfile=r.data}updateUi()}
async function initialize(){if(initialized)return;initialized=true;bindUi();if(!configured()||!window.supabase?.createClient){updateUi();return}client=window.supabase.createClient(config.url.trim(),config.anonKey.trim(),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error}=await client.auth.getSession();if(error)console.warn(error.message);currentUser=data?.session?.user||null;if(currentUser)await loadProfile();else updateUi();client.auth.onAuthStateChange((event,session)=>setTimeout(async()=>{currentUser=session?.user||null;if(currentUser)await loadProfile();else{currentProfile=null;updateUi()}if(event==='PASSWORD_RECOVERY'&&session){openProfile(true)}},0))}
async function signIn(){if(!client)throw new Error('Cloud accounts are not configured. You can continue as guest.');const email=String($('authEmail')?.value||'').trim(),password=String($('authPassword')?.value||'');if(!email||!password)throw new Error('Enter your email and password.');msg('Signing in…');const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;msg('Signed in. Loading your cloud projects…','success');setTimeout(()=>location.reload(),350)}
async function signUp(){if(!client)throw new Error('Cloud accounts are not configured.');const email=String($('authSignupEmail')?.value||'').trim(),password=String($('authSignupPassword')?.value||''),displayName=String($('authSignupName')?.value||'').trim();if(!email||!password)throw new Error('Enter an email and password.');if(password.length<8)throw new Error('Use at least 8 characters for the password.');msg('Creating your account…');const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:displayName}}});if(error)throw error;if(data.session){msg('Account created. Loading your workspace…','success');setTimeout(()=>location.reload(),350)}else{setView('authSignInView');if($('authEmail'))$('authEmail').value=email;msg('Account created. Check your email to confirm it, then sign in.','success')}}
async function resetPassword(){if(!client)throw new Error('Cloud accounts are not configured.');const email=String($('authForgotEmail')?.value||'').trim();if(!email)throw new Error('Enter your email address.');const redirectTo=`${location.origin}${location.pathname}`;const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo});if(error)throw error;msg('Reset link sent. Check your email inbox.','success')}
async function signOut(){if(client)await client.auth.signOut();location.reload()}
function openProfile(recovery=false){updateUi();profileMsg(recovery?'Enter a new password below to finish password recovery.':'');const d=$('profileDialog');if(d&&!d.open)d.showModal()}
async function saveProfile(){if(!client||!currentUser)return;const displayName=String($('profileDisplayName')?.value||'').trim(),newEmail=String($('profileEmail')?.value||'').trim(),newPassword=String($('profileNewPassword')?.value||'');profileMsg('Saving…');const r=await client.from('profiles').upsert({id:currentUser.id,display_name:displayName,updated_at:nowIso()}).select('id,display_name,created_at,updated_at').single();if(r.error)throw r.error;currentProfile=r.data;const updates={data:{display_name:displayName}};if(newEmail&&newEmail.toLowerCase()!==String(currentUser.email||'').toLowerCase())updates.email=newEmail;if(newPassword){if(newPassword.length<8)throw new Error('Use at least 8 characters.');updates.password=newPassword}const u=await client.auth.updateUser(updates);if(u.error)throw u.error;currentUser=u.data.user||currentUser;if($('profileNewPassword'))$('profileNewPassword').value='';updateUi();profileMsg(updates.email?'Saved. Check the new email address for confirmation.':'Profile saved.','success')}
function requireUser(){if(!currentUser)throw new Error('Sign in to use cloud project storage.');return currentUser}
async function listProjects(){const u=requireUser(),r=await client.from('projects').select('id,data,updated_at').eq('user_id',u.id).order('updated_at',{ascending:false});if(r.error)throw r.error;return(r.data||[]).map(x=>({...x.data,id:x.id})).filter(x=>x.id)}async function getProject(id){const u=requireUser(),r=await client.from('projects').select('id,data').eq('user_id',u.id).eq('id',String(id)).maybeSingle();if(r.error)throw r.error;return r.data?{...r.data.data,id:r.data.id}:undefined}async function putProject(p){const u=requireUser();if(!p?.id)throw new Error('Project id is required.');const payload={user_id:u.id,id:String(p.id),name:String(p.name||'Untitled project'),customer:String(p.customer||''),archived:!!p.archived,created_at:p.createdAt||nowIso(),updated_at:p.updatedAt||nowIso(),data:p};const r=await client.from('projects').upsert(payload,{onConflict:'user_id,id'});if(r.error)throw r.error;return p}async function deleteProject(id){const u=requireUser(),r=await client.from('projects').delete().eq('user_id',u.id).eq('id',String(id));if(r.error)throw r.error}async function clearProjects(){const u=requireUser(),r=await client.from('projects').delete().eq('user_id',u.id);if(r.error)throw r.error}
function bindUi(){const signIn=$('authSignInForm');if(signIn)signIn.onsubmit=async e=>{e.preventDefault();try{await signIn()}catch(err){msg(err.message||'Could not sign in.','error')}};const signup=$('authSignUpForm');if(signup)signup.onsubmit=async e=>{e.preventDefault();try{await signUp()}catch(err){msg(err.message||'Could not create account.','error')}};const forgot=$('authForgotForm');if(forgot)forgot.onsubmit=async e=>{e.preventDefault();try{await resetPassword()}catch(err){msg(err.message||'Could not send reset link.','error')}};if($('btnShowSignUp'))$('btnShowSignUp').onclick=()=>setView('authSignUpView');if($('btnShowSignIn'))$('btnShowSignIn').onclick=()=>setView('authSignInView');if($('btnShowForgot'))$('btnShowForgot').onclick=()=>{$('authForgotEmail').value=$('authEmail')?.value||'';setView('authForgotView')};if($('btnBackSignIn'))$('btnBackSignIn').onclick=()=>setView('authSignInView');if($('btnContinueGuest'))$('btnContinueGuest').onclick=closeAccount;if($('btnProfileHeader'))$('btnProfileHeader').onclick=()=>openAccount();if($('btnProfile'))$('btnProfile').onclick=()=>openAccount();if($('btnSignOut'))$('btnSignOut').onclick=signOut;if($('btnProfileSignOut'))$('btnProfileSignOut').onclick=signOut;if($('btnSaveProfile'))$('btnSaveProfile').onclick=async()=>{try{await saveProfile()}catch(err){profileMsg(err.message||'Could not save profile.','error')}};document.querySelectorAll('[data-close-account]').forEach(b=>b.onclick=closeAccount)}
window.GROHEAuth=Object.freeze({initialize,isConfigured:configured,isSignedIn:()=>!!currentUser,getUser:()=>currentUser,getProfile:()=>currentProfile,getClient:()=>client,openAccount,openProfile,signOut,listProjects,getProject,putProject,deleteProject,clearProjects});
})();
