(() => {
'use strict';
const {PDFDocument,StandardFonts,rgb}=PDFLib,$=id=>document.getElementById(id),norm=v=>String(v||'').replace(/[^0-9A-Za-z]/g,'').toUpperCase(),safe=v=>String(v||'Project').replace(/[\\/:*?"<>|]+/g,'-').trim();
const state={items:[],extras:[],repo:[],handle:null,folderName:'',drag:-1};
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
const Store={open(){return new Promise((res,rej)=>{const r=indexedDB.open('GROHEPdfLibrary',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('settings'))r.result.createObjectStore('settings')};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})},async get(){try{const db=await this.open();return await new Promise((res,rej)=>{const r=db.transaction('settings','readonly').objectStore('settings').get('pdf-folder');r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}catch{return null}},async set(h){try{const db=await this.open();await new Promise((res,rej)=>{const r=db.transaction('settings','readwrite').objectStore('settings').put(h,'pdf-folder');r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}catch{}}};
async function walk(dir,p=''){const a=[];for await(const [n,h] of dir.entries()){if(h.kind==='directory')a.push(...await walk(h,p+n+'/'));else if(h.kind==='file'&&n.toLowerCase().endsWith('.pdf'))a.push({name:n,path:p+n,handle:h,key:n.toLowerCase(),normalised:norm(n.replace(/\.pdf$/i,'')),bytes:null,pages:0})}return a}
function similarity(q,f){q=norm(q);f=norm(f);if(!q||!f)return 0;if(f===q||f.includes(q))return 1;const ed=(a,b)=>{let d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]};let best=0;if(f.length<=q.length+2)best=1-ed(q,f)/Math.max(q.length,f.length);else for(let i=0;i<=f.length-q.length;i++)best=Math.max(best,1-ed(q,f.slice(i,i+q.length))/q.length);return Math.max(0,best)}
function findMatch(item){const q=norm(item.name);if(item.linkedKey){const x=state.repo.find(r=>r.key===item.linkedKey);if(x)return{pdf:x,confidence:1,accepted:true,exact:false}}let best=null;for(const pdf of state.repo){let score=similarity(q,pdf.normalised),exact=pdf.normalised===q||pdf.normalised.includes(q);if(exact)score=1;if(!best||score>best.confidence)best={pdf,confidence:score,exact,accepted:false}}return best&&best.confidence>=.64?best:null}
async function ensurePdf(pdf){if(pdf.bytes)return pdf;const f=await pdf.handle.getFile();const bytes=new Uint8Array(await f.arrayBuffer());if(String.fromCharCode(...bytes.slice(0,5))!=='%PDF-')throw new Error(`${pdf.name} is not a valid PDF`);const d=await PDFDocument.load(bytes.slice());pdf.bytes=bytes;pdf.pages=d.getPageCount();return pdf}
async function scan(h){state.handle=h;state.folderName=h.name||'Data Sheets';state.repo=await walk(h);$('folderPath').textContent=state.folderName;$('pdfCount').textContent=state.repo.length;renderLibrary();renderSequence();toast(`Indexed ${state.repo.length} PDFs`)}
async function chooseFolder(){if(!window.showDirectoryPicker){toast('Use Chrome or Edge to select a folder');return}try{const h=await showDirectoryPicker({mode:'read'});await Store.set(h);await scan(h)}catch(e){if(e.name!=='AbortError')toast(e.message)}}
async function restoreFolder(){const h=await Store.get();if(!h)return;try{if(await h.queryPermission({mode:'read'})==='granted')await scan(h)}catch{}}
function renderLibrary(){const q=$('libSearch').value.trim().toLowerCase();$('libraryList').innerHTML=state.repo.filter(x=>!q||x.name.toLowerCase().includes(q)).slice(0,500).map(x=>`<div class="lib-row" title="${x.path}">${x.name}</div>`).join('')}
function transfer(){try{return JSON.parse(sessionStorage.getItem('grohe-pdfkit-transfer')||'null')}catch{return null}}
function loadTransfer(){const t=transfer();if(!t)return;state.items=(t.items||[]).map((x,i)=>({id:x.id||`${Date.now()}-${i}`,type:x.type==='separator'?'separator':'file',name:x.name||x.sku||'',description:x.description||''}));$('projectName').value=t.projectName||'';$('selectionName').value=t.selectionName||'Selection';$('coverSubtitle').value=t.customer?`${t.customer} · ${t.selectionName||'Selection'}`:(t.selectionName||'Selection');$('projectBadge').textContent=[t.projectName,t.selectionName].filter(Boolean).join(' · ')||'Project';$('selectionMeta').textContent=`${state.items.filter(x=>x.type==='file').length} product data sheets · ${t.selectionName||'Selection'}`;renderSequence()}
function renderSequence(){const list=$('sequenceList');$('emptyState').style.display=state.items.length?'none':'flex';let linked=0,missing=0;list.innerHTML=state.items.map((item,i)=>{if(item.type==='separator')return `<div class="seq-row break" draggable="true" data-i="${i}"><span class="drag">⠿</span><div class="seq-main"><strong>${item.name}</strong><span>Break divider</span></div><div></div></div>`;const m=findMatch(item);let status='Missing',cls='missing',actions='';if(m?.exact||m?.accepted){status='Linked';cls='';linked++;actions=`<button class="mini" data-preview="${i}">Preview</button>`}else if(m?.pdf){status=`Suggested ${Math.round(m.confidence*100)}%`;cls='suggest';missing++;actions=`<button class="mini" data-link="${i}">Link</button>`}else missing++;return `<div class="seq-row" draggable="true" data-i="${i}"><span class="drag">⠿</span><div class="seq-main"><strong>${item.name}</strong><span>${item.description||m?.pdf?.name||'GROHE product data sheet'}</span></div><div class="seq-actions"><span class="status ${cls}">${status}</span>${actions}</div></div>`}).join('');$('linkedChip').textContent=`${linked} linked`;$('missingChip').textContent=`${missing} missing`;$('verifyStatus').className=`verify ${missing?'bad':'good'}`;$('verifyStatus').textContent=state.items.length?(missing?`${missing} product data sheet${missing===1?' is':'s are'} still missing or need approval.`:`All ${linked} product data sheets are linked.`):'No products in the sequence.';list.querySelectorAll('[data-link]').forEach(b=>b.onclick=()=>{const i=+b.dataset.link,m=findMatch(state.items[i]);if(m?.pdf){state.items[i].linkedKey=m.pdf.key;renderSequence()}});list.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>previewItem(+b.dataset.preview));bindDrag()}
function bindDrag(){document.querySelectorAll('.seq-row').forEach(r=>{r.ondragstart=()=>state.drag=+r.dataset.i;r.ondragover=e=>e.preventDefault();r.ondrop=e=>{e.preventDefault();const to=+r.dataset.i;if(state.drag<0||to===state.drag)return;const [x]=state.items.splice(state.drag,1);state.items.splice(to,0,x);state.drag=-1;renderSequence()}})}
async function previewItem(i){const m=findMatch(state.items[i]);if(!m?.pdf)return;try{const p=await ensurePdf(m.pdf),blob=new Blob([p.bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob);$('previewTitle').textContent=state.items[i].name;$('previewMeta').textContent=p.name;$('previewFrame').src=url;$('previewDialog').showModal();$('previewDialog').dataset.url=url}catch(e){toast(e.message)}}
async function buildCover(doc,fontB,font){const page=doc.addPage([595.28,841.89]);page.drawRectangle({x:0,y:0,width:595.28,height:841.89,color:rgb(.02,.24,.41)});const title=$('coverTitle').value||'Technical Data Sheet',project=$('projectName').value||'Project',selection=$('selectionName').value||'Selection';page.drawText(title,{x:48,y:520,size:30,font:fontB,color:rgb(1,1,1)});page.drawText(project,{x:48,y:478,size:18,font:font,color:rgb(.85,.94,1)});page.drawText(selection,{x:48,y:450,size:12,font:font,color:rgb(.72,.86,.95)});const sub=$('coverSubtitle').value;if(sub)page.drawText(sub,{x:48,y:420,size:10,font,color:rgb(.85,.9,.95)});const author=$('author').value,date=$('date').value;page.drawText([author,date].filter(Boolean).join(' · '),{x:48,y:70,size:9,font,color:rgb(.85,.9,.95)})}
async function buildDivider(doc,fontB,text){const p=doc.addPage([595.28,841.89]);p.drawRectangle({x:0,y:0,width:595.28,height:841.89,color:rgb(.93,.96,.98)});p.drawText(String(text||'Section'),{x:60,y:430,size:24,font:fontB,color:rgb(.02,.24,.41)})}
async function exportPdf(){const files=state.items.filter(x=>x.type==='file');if(!files.length){toast('No product data sheets to export');return}const missing=state.items.filter(x=>x.type==='file'&&!(()=>{const m=findMatch(x);return m&&(m.exact||m.accepted)})());if(missing.length){toast(`Fix ${missing.length} missing PDF${missing.length===1?'':'s'} first`);return}const btn=$('exportBtn');btn.disabled=true;btn.textContent='Building PDF…';try{const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),fontB=await doc.embedFont(StandardFonts.HelveticaBold);if($('coverEnabled').checked)await buildCover(doc,fontB,font);let tocPage=null,tocRows=[];if($('tocEnabled').checked){tocPage=doc.addPage([595.28,841.89]);tocPage.drawText('Table of Contents',{x:54,y:790,size:20,font:fontB,color:rgb(.08,.14,.2)})}let sequenceNo=0;for(const item of state.items){if(item.type==='separator'){if($('dividerEnabled').checked)await buildDivider(doc,fontB,item.name);continue}sequenceNo++;btn.textContent=`Loading ${sequenceNo}/${files.length}…`;const m=findMatch(item),pdf=await ensurePdf(m.pdf),src=await PDFDocument.load(pdf.bytes.slice()),pages=await doc.copyPages(src,src.getPageIndices()),start=doc.getPageCount()+1;pages.forEach(p=>doc.addPage(p));tocRows.push({name:item.name,page:start})}for(const ex of state.extras){const bytes=new Uint8Array(await ex.arrayBuffer()),src=await PDFDocument.load(bytes),pages=await doc.copyPages(src,src.getPageIndices());pages.forEach(p=>doc.addPage(p))}if(tocPage){let y=755;for(let i=0;i<tocRows.length;i++){if(y<55)break;const r=tocRows[i],name=(r.name||'').slice(0,50);tocPage.drawText(`${i+1}. ${name}`,{x:60,y,size:9,font,color:rgb(.12,.16,.23)});tocPage.drawText(String(r.page),{x:515,y,size:9,font,color:rgb(.35,.4,.45)});y-=19}}if($('pageNums').checked){const pages=doc.getPages();pages.forEach((p,i)=>{if(i===0&&$('coverEnabled').checked)return;const t=String(i+1);p.drawText(t,{x:292,y:20,size:8,font,color:rgb(.45,.5,.56)})})}const bytes=await doc.save({useObjectStreams:true}),blob=new Blob([bytes],{type:'application/pdf'}),a=document.createElement('a'),project=safe($('projectName').value),selection=safe($('selectionName').value),fname=`${project}${selection?` - ${selection}`:''} Technical Data Sheet.pdf`;a.href=URL.createObjectURL(blob);a.download=fname;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);toast(`Exported ${doc.getPageCount()} pages`)}catch(e){console.error(e);toast(`Export stopped: ${e.message}`)}finally{btn.disabled=false;btn.textContent='Export PDF'}}
$('folderBtn').onclick=chooseFolder;$('libSearch').oninput=renderLibrary;$('verifyBtn').onclick=renderSequence;$('exportBtn').onclick=exportPdf;$('backBtn').onclick=()=>history.length>1?history.back():location.href='../';$('previewClose').onclick=()=>$('previewDialog').close();$('previewDialog').addEventListener('close',()=>{const u=$('previewDialog').dataset.url;if(u)URL.revokeObjectURL(u);$('previewFrame').src='about:blank'});$('extraDrop').onclick=()=>$('extraFiles').click();$('extraFiles').onchange=e=>{state.extras.push(...[...(e.target.files||[])]);toast(`${e.target.files.length} extra PDF${e.target.files.length===1?'':'s'} added`)};$('date').value=new Date().toISOString().slice(0,10);loadTransfer();restoreFolder();
})();
