from pathlib import Path
import sys

app_path = Path(sys.argv[1])
html_path = Path(sys.argv[2])

app = app_path.read_text(encoding="utf-8")
html = html_path.read_text(encoding="utf-8")

button_anchor = '<button class="btn small" id="btnAddSection2">+ Break</button>'
button_markup = '<button class="btn small auto-breaks-btn" id="btnAutoBreaks" title="Automatically group selected items into WC, Basin Mixer, Shower Set and Accessories">Auto Breaks</button>\\n            ' + button_anchor
if 'id="btnAutoBreaks"' not in html:
    if button_anchor not in html:
        raise SystemExit("Could not find + Break button")
    html = html.replace(button_anchor, button_markup, 1)

auto_code = r"""
const AUTO_BREAK_DEFS=[
  {key:'wc',title:'WC'},
  {key:'basin',title:'Basin Mixer'},
  {key:'shower',title:'Shower Set'},
  {key:'accessories',title:'Accessories'}
];

function autoBreakClassForProduct(product){
  if(!product)return '';
  const cat=normalizeText(product.category||'');
  const raw=[product.description,product.fullText,product.family,product.category,product.area,product.function,product.mounting].filter(Boolean).join(' ');
  const hay=normalizeText(raw);

  // WC: flushing systems, actuation, inspection shafts, trigger sprays and WC ceramics.
  if(cat==='flush plate / actuation' || cat==='flushing system' || cat==='wc / ceramic' || cat==='shower toilet' ||
     cat==='trigger spray' || /inspection shaft|revision shaft|flush tank|flushtank|flushing cistern/.test(hay)){
    return 'wc';
  }

  // Basin Mixer: mixers plus the standard project angle valve and bottle trap.
  const standardAngle=/angle valve/.test(hay) && (
    /1\s*\/\s*2[^0-9]{0,12}3\s*\/\s*8/i.test(raw) ||
    /1 2[^0-9]{0,12}3 8/.test(hay)
  );
  if(cat==='basin mixer' || standardAngle || /bottle trap/.test(hay)) return 'basin';

  // Shower Set: shower controls, rain/head/hand showers, hoses, holders/outlets,
  // rails/systems and the concealed parts that belong to shower controls.
  const showerCats=new Set(['head shower','hand shower','shower system','shower set / rail','shower mixer','shower hose','shower accessory','body spray']);
  const showerRoughIn=cat==='concealed / rough-in' && /shower|smartbox|rapido|thermost|diverter/.test(hay) && !/basin/.test(hay);
  if(showerCats.has(cat) || showerRoughIn || /rainshower|head shower|headshower|hand shower|handshower|shower hose|outlet elbow|shower holder|wall holder/.test(hay)){
    return 'shower';
  }

  // Generic bathroom accessories are last so special WC / basin / shower accessories
  // above always win first.
  if(cat==='accessory' || /\baccessor(?:y|ies)\b/.test(cat) || /\bbathroom accessor(?:y|ies)\b/.test(hay)) return 'accessories';

  return '';
}

function autoBreakItemBlocks(items=[]){
  const products=items.filter(x=>x?.type==='product');
  const byId=new Map(products.map(x=>[x.id,x]));
  const children=new Map();
  products.filter(x=>x.auto&&x.parentItemId).forEach(child=>{
    if(!children.has(child.parentItemId))children.set(child.parentItemId,[]);
    children.get(child.parentItemId).push(child);
  });
  const seen=new Set(),blocks=[];
  for(const item of products){
    if(seen.has(item.id))continue;
    if(item.auto && item.parentItemId && byId.has(item.parentItemId))continue;
    const block=[item,...(children.get(item.id)||[])];
    block.forEach(x=>seen.add(x.id));
    blocks.push(block);
  }
  // Keep any orphan auto item rather than dropping it.
  for(const item of products){
    if(!seen.has(item.id)){seen.add(item.id);blocks.push([item]);}
  }
  return blocks;
}

async function autoCreateBreaks(){
  if(!state.project){openProjectDialog('new');return;}
  await ensureRequiredComponents(false);
  const blocks=autoBreakItemBlocks(state.project.items||[]);
  if(!blocks.length){toast('Add products before creating automatic breaks');return;}

  pushProjectHistory('Auto-create WC, Basin Mixer, Shower Set and Accessories breaks');

  const grouped=new Map(AUTO_BREAK_DEFS.map(def=>[def.key,[]]));
  const unmatched=[];
  for(const block of blocks){
    const parent=block.find(x=>!x.auto)||block[0];
    const product=getProduct(parent?.sku);
    const key=autoBreakClassForProduct(product);
    if(key && grouped.has(key))grouped.get(key).push(...block);
    else unmatched.push(...block);
  }

  const generated=[];
  for(const def of AUTO_BREAK_DEFS){
    generated.push({id:uid(),type:'section',title:def.title,autoGenerated:true});
    generated.push(...grouped.get(def.key));
  }
  state.project.items=[...unmatched,...generated];
  await touchProject();
  renderProject();
  renderResults();

  const counts=AUTO_BREAK_DEFS.map(def=>def.title+': '+grouped.get(def.key).filter(x=>x.type==='product'&&!x.auto).length).join(' · ');
  toast('Auto breaks created · '+counts+(unmatched.length?' · unmatched items kept above breaks':''));
}
"""

if 'function autoCreateBreaks()' not in app:
    anchor = "async function addSection(){"
    if anchor not in app:
        raise SystemExit("Could not find addSection")
    app = app.replace(anchor, auto_code + "\n" + anchor, 1)

event_anchor = "$('btnAddSection').onclick=addSection; $('btnAddSection2').onclick=addSection; $('btnClearSequence').onclick=clearSequence;"
event_new = "$('btnAddSection').onclick=addSection; $('btnAddSection2').onclick=addSection; if($('btnAutoBreaks')) $('btnAutoBreaks').onclick=autoCreateBreaks; $('btnClearSequence').onclick=clearSequence;"
if "btnAutoBreaks')) $('btnAutoBreaks').onclick=autoCreateBreaks" not in app:
    if event_anchor not in app:
        raise SystemExit("Could not find section event wiring")
    app = app.replace(event_anchor, event_new, 1)

# Make the inline break editor follow the break-name length.
old_editor = "const input=document.createElement('input'); input.className='room-name-editor'; input.value=item.title||''; input.setAttribute('aria-label','Break name');"
new_editor = "const input=document.createElement('input'); input.className='room-name-editor'; input.value=item.title||''; input.size=Math.max(6,Math.min(34,String(item.title||'').length+2)); input.setAttribute('aria-label','Break name'); input.addEventListener('input',()=>{input.size=Math.max(6,Math.min(34,input.value.length+2));});"
if old_editor in app:
    app = app.replace(old_editor, new_editor, 1)

app_path.write_text(app, encoding="utf-8")
html_path.write_text(html, encoding="utf-8")
